# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .vellum_document_request import VellumDocumentRequest
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class DocumentChatMessageContentRequest(UniversalBaseModel):
    """
    A document value that is used in a chat message.
    """

    type: typing.Literal["DOCUMENT"] = "DOCUMENT"
    value: VellumDocumentRequest

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
