# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
import typing
from .jinja_prompt_block import JinjaPromptBlock
from .variable_prompt_block import VariablePromptBlock
from .rich_text_prompt_block import RichTextPromptBlock
from .audio_prompt_block import AudioPromptBlock
from .function_call_prompt_block import FunctionCallPromptBlock
from .image_prompt_block import ImagePromptBlock
from .document_prompt_block import DocumentPromptBlock
import typing

if typing.TYPE_CHECKING:
    from .chat_message_prompt_block import ChatMessagePromptBlock
PromptBlock = typing.Union[
    JinjaPromptBlock,
    "ChatMessagePromptBlock",
    VariablePromptBlock,
    RichTextPromptBlock,
    AudioPromptBlock,
    FunctionCallPromptBlock,
    ImagePromptBlock,
    DocumentPromptBlock,
]
