# This file was auto-generated by Fern from our API Definition.

from vellum import Vellum
from vellum import AsyncVellum
import typing
from .utilities import validate_response


async def test_workspace_identity(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {"id": "id", "name": "name", "label": "label", "created": "2024-01-15T09:30:00Z"}
    expected_types: typing.Any = {"id": None, "name": None, "label": None, "created": "datetime"}
    response = client.workspaces.workspace_identity()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.workspaces.workspace_identity()
    validate_response(async_response, expected_response, expected_types)
