# This file was auto-generated by Fern from our API Definition.

from vellum import Vellum
from vellum import AsyncVellum
import typing
from .utilities import validate_response


async def test_organization_identity(client: Vellum, async_client: AsyncVellum) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "name": "name",
        "allow_staff_access": True,
        "new_member_join_behavior": "AUTO_ACCEPT_FROM_SHARED_DOMAIN",
    }
    expected_types: typing.Any = {
        "id": None,
        "name": None,
        "allow_staff_access": None,
        "new_member_join_behavior": None,
    }
    response = client.organizations.organization_identity()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.organizations.organization_identity()
    validate_response(async_response, expected_response, expected_types)
